In [47]:
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException
from pandas import *
import time

In [53]:
teams = ['ATL', 'BOS', 'BRK', 'CHO', 'CHI', 'CLE', 'DAL', 'DEN', 'DET', 'GSW', 'HOU', 'IND', 'LAC', 'LAL',
                 'MEM', 'MIA', 'MIL', 'MIN', 'NOP', 'NYK', 'OKC', 'ORL', 'PHI', 'PHO', 'POR', 'SAC', 'SAS', 'TOR',
                 'UTA', 'WAS']
team_player = {}
team_player_url = {}
dr = webdriver.Chrome('/Users/joono/chromedriver')
for team in teams:
    url = 'https://www.basketball-reference.com/teams/'+team+'/2019.html'
    dr.get(url)
    players = []
    players_url = []
    players_el = dr.find_elements_by_css_selector('td[data-stat = "player"]')
    for pl_el in players_el:
        players.append(pl_el.text)
        players_url.append(pl_el.find_element_by_tag_name('a').get_attribute('href'))
    if players == []:
        print(team,'잘못됨')
    team_player.update({team:list(unique(players))})
    team_player_url.update({team:list(unique(players_url))})

In [74]:
G = []
Date = []
Age = []
Tm =[]
at=[]
Opp=[]
wl=[]
GS=[]
MP=[]
FG=[]
FGA=[]
FGper=[]
three_P=[]
three_PA=[]
three_Pper=[]
FT=[]
FTA=[]
FTper=[]
ORB=[]
DRB=[]
TRB=[]
AST=[]
STL=[]
BLK=[]
TOV=[]
PF=[]
PTS=[]
GmSc=[]
plus=[]
stats = [G,
Date,
Age,
Tm,
at,
Opp,
wl,
GS,
MP,
FG,
FGA,
FGper,
three_P,
three_PA,
three_Pper,
FT,
FTA,
FTper,
ORB,
DRB,
TRB,
AST,
STL,
BLK,
TOV,
PF,
PTS,
GmSc,
plus]
team_col = []
name_col = []
dr = webdriver.Chrome('/Users/joono/chromedriver')
nowtime time.time()
for team in teams[:1]:
    urls = [x[:-5]+'/gamelog/2018' for x in team_player_url[team]]
    for idx,url in enumerate(urls[:1]):
        dr.get(url)
        table = dr.find_element_by_css_selector('table[class = "row_summable sortable stats_table now_sortable"]')
        tbody = table.find_element_by_css_selector('tbody')
        trs = tbody.find_elements_by_css_selector('tr')
        for tr in trs:
            tds = tr.find_elements_by_css_selector('td')
            if len(tds) != 0:
                if tds[0].text != '':
                    for i in range(0,len(stats)):
                        try:
                            if tds[i].text != '':
                                stats[i].append(tds[i].text)
                            else:
                                stats[i].append('none')
                        except IndexError:
                            stats[i].append('none')

                else:
                    for i in range(0,len(stats[:8])):
                        try:
                            if tds[i].text != '':
                                stats[i].append(tds[i].text)
                            else:
                                stats[i].append('no_play')
                        except IndexError:
                            stats[i].append('no_play')

                    for j in range(8,len(stats)):
                        stats[j].append('no_play')
                team_col.append(team)
                name_col.append(team_player[team][idx])
            else:
                continue
dt = DataFrame({'G' : G,
            'Date' : Date,
            'Age' : Age,
            'Tm' : Tm,
            'at' : at,
            'Opp' : Opp,
            'wl' : wl,
            'GS' : GS,
            'MP' : MP,
            'FG' : FG,
            'FGA' : FGA,
            'FGper' : FGper,
            'three_P' : three_P,
            'three_PA' : three_PA,
            'three_Pper' : three_Pper,
            'FT' : FT,
            'FTA' : FTA,
            'FTper' : FTper,
            'ORB' : ORB,
            'DRB' : DRB,
            'TRB' : TRB,
            'AST' : AST,
            'STL' : STL,
            'BLK' : BLK,
            'TOV' : TOV,
            'PF' : PF,
            'PTS' : PTS,
            'GmSc' : GmSc,
            'plus' : plus,
            'team' : team_col,
           'name' : name_col})
endtime = time.time() - nowtime
print(endtime)
print('done')

In [75]:
dt.head()

,AST,Age,BLK,DRB,Date,FG,FGA,FGper,FT,FTA,...,TRB,Tm,at,name,plus,team,three_P,three_PA,three_Pper,wl
0,no_play,23-333,no_play,no_play,2017-10-18,no_play,no_play,no_play,no_play,no_play,...,no_play,PHI,@,Justin Anderson,no_play,ATL,no_play,no_play,no_play,L (-5)
1,0,23-335,0,0,2017-10-20,0,0,none,0,0,...,0,PHI,none,Justin Anderson,-4,ATL,0,0,none,L (-10)
2,0,23-336,1,0,2017-10-21,4,12,.333,2,4,...,1,PHI,@,Justin Anderson,-14,ATL,2,7,.286,L (-34)
3,no_play,23-338,no_play,no_play,2017-10-23,no_play,no_play,no_play,no_play,no_play,...,no_play,PHI,@,Justin Anderson,no_play,ATL,no_play,no_play,no_play,W (+11)
4,0,23-340,0,3,2017-10-25,3,7,.429,0,0,...,3,PHI,none,Justin Anderson,-13,ATL,2,5,.400,L (-1)